config/routes.rb
OpenProject::Application.routes.draw do

  scope 'projects/:project_id' do
    resources :project_groups, controller: 'project_groups', :except => [:index] do
      member do
        post :remove_user
        post :add_users

        #Possible needed, they are part of OpenProject for Group  
              
        get :autocomplete_for_user
#        # this should be put into it's own resource
#        match '/members' => 'project_groups#add_users', via: :post, as: 'members_of'
#        match '/members/:user_id' => 'project_groups#remove_user', via: :delete, as: 'member_of'
#        # this should be put into it's own resource
#        match '/memberships/:membership_id' => 'project_groups#edit_membership', via: :put, as: 'membership_of'
#        match '/memberships/:membership_id' => 'project_groups#destroy_membership', via: :delete, as: 'membership_of'
#        match '/memberships' => 'project_groups#create_memberships', via: :post, as: 'memberships_of'
        
      end
    end
  end

end

app/views/projects/settings/_project_groups.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2017 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>
<%#--Fom the original app/views/groups/index.html.erb++#%>

<%#--html_title l(:label_administration), l("label_group_plural") ++#%>
<%= toolbar title: "" do %>
  <li class="toolbar-item">
    <%= link_to_if_authorized({ controller: '/project_groups', action: 'new', project_id: @project }, 
            class: 'button -alt-highlight',
            aria: {label: t(:label_group_new)},
            title: t(:label_group_new)) do %>
      <%= op_icon('button--icon icon-add') %>
      <span class="button--text"><%= t('activerecord.models.group') %></span>
    <% end %>
  </li>
<% end %>
<% if @project_groups.any? %>
  <div class="generic-table--container">
    <div class="generic-table--results-container">
      <table class="generic-table">
        <colgroup>
          <col highlight-col>
          <col highlight-col>
          <col highlight-col>
          <col>
        </colgroup>
        <thead>
          <tr>
            <th>
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= Group.model_name.human %>
                  </span>
                </div>
              </div>
            </th>
            <th>
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%=l(:label_user_plural)%>
                  </span>
                </div>
              </div>
            </th>
            <th>
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= "Parent project" %>
                  </span>
                </div>
              </div>
            </th>
            <th><div class="generic-table--empty-header"></div></th>
          </tr>
        </thead>
        <tbody>
          <% @project_groups.each do |group| %>
            <tr>
              <% if group.is_child_of?(@project) %>
                <td><%= link_to h(group), edit_project_group_path(@project, group) %></td>
              <% else %>
                <td><%= link_to h(group), project_group_path(@project, group), class: "icon icon-locked" %></td>
              <% end %>
              <td><%= group.users.size %></td>
              <td class="parent_project"><%= link_to group.parent_project, project_path(group.parent_project) %></td>
              <% if group.is_child_of?(@project) %>
                <td class="buttons"><%= link_to l(:button_delete), project_group_path(@project, group), data: { confirm: l(:text_are_you_sure) }, method: :delete, class: 'icon icon-delete' %></td>
              <% else %>
                <td class="buttons"></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      
    </div>
  </div>
<% else %>
  <%= no_results_box(action_url: { controller: '/project_groups', action: 'new', project_id: @project },
                     display_action: authorize_for(:project_groups, :new)) %>
<% end %>