config/routes.rb
OpenProject::Application.routes.draw do

  scope 'projects/:project_id' do
    resources :project_groups, controller: 'project_groups', :except => [:index] do
      member do
        post :remove_user
        post :add_users

        #Possible needed, they are part of OpenProject for Group  
              
        get :autocomplete_for_user
#        # this should be put into it's own resource
#        match '/members' => 'project_groups#add_users', via: :post, as: 'members_of'
#        match '/members/:user_id' => 'project_groups#remove_user', via: :delete, as: 'member_of'
#        # this should be put into it's own resource
#        match '/memberships/:membership_id' => 'project_groups#edit_membership', via: :put, as: 'membership_of'
#        match '/memberships/:membership_id' => 'project_groups#destroy_membership', via: :delete, as: 'membership_of'
#        match '/memberships' => 'project_groups#create_memberships', via: :post, as: 'memberships_of'
        
      end
    end
  end

end

app/models/project_group.rb
# -*- encoding : utf-8 -*-
class ProjectGroup < Group
  unloadable

  has_many :project_group_scopes, :dependent => :destroy
  has_many :projects, -> { uniq }, :through => :project_group_scopes
  belongs_to :parent_project, :foreign_key => 'project_group_project_id', :class_name => 'Project'

  validates_presence_of :parent_project

  after_create :add_to_descendants

  def is_child_of?(project)
    project_id = project.is_a?(Project) ? project.id : project.to_i
    project_id == parent_project.id
  end

  private

  # Once a group is created, it should be available to all
  # subprojects of the parent project
  def add_to_descendants
    parent_project.descendants.each do |project|
      project.project_groups << self
    end
  end

end

app/controllers/project_groups_controller.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2017 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2017 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

class ProjectGroupsController < ApplicationController
  unloadable
  model_object ProjectGroup
  before_action :find_project_by_project_id
  before_action :authorize
  before_action :find_model_object, :except => [:new, :create] #=> @project_group
  before_action :authorize_manageable, :except => [:new, :create, :show]

  # GET /groups
  # GET /groups.xml
  def index






  end

  # GET /groups/1
  # GET /groups/1.xml
  def show




  end

  # GET /groups/new
  # GET /groups/new.xml
  def new
    @project_group = ProjectGroup.new(projects: [@project])





  end

  # GET /groups/1/edit
  def edit
    load_users
  end

  # POST /groups
  # POST /groups.xml
  def create
    @project_group = ProjectGroup.new(lastname: params[:project_group][:lastname])
    @project_group.parent_project = @project
    @project_group.projects << @project #TODO this could be handled by model on create

    respond_to do |format|
      if @project_group.save
        # Group is manageable for the project in which was created
        flash[:notice] = l(:notice_successful_create)
        format.html do redirect_to(controller: "projects", action: "settings", id: @project, tab: "project_groups") end
        format.xml  do render xml: @project_group, status: :created, location: @project_group end
      else
        format.html do render action: 'new' end
        format.xml  do render xml: @project_group.errors, status: :unprocessable_entity end
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.xml
  def update


    respond_to do |format|
      if @project_group.update_attributes(lastname: params[:project_group][:lastname])
        flash[:notice] = l(:notice_successful_update)
        format.html do redirect_to(edit_project_group_url(@project, @project_group)) end
        format.xml  do head :ok end
      else
        load_users
        format.html do render action: 'edit' end
        format.xml  do render xml: @project_group.errors, status: :unprocessable_entity end
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.xml
  def destroy
    @project_group.destroy

    respond_to do |format|
      flash[:notice] = l(:notice_successful_delete)
      format.html do redirect_to(controller: "projects", action: "settings", id: @project, tab: "project_groups") end
      format.xml  do head :ok end
    end
  end

  def add_users

    @users = User.includes(:memberships).where(id: params[:user_ids])
    @project_group.users << @users
    respond_to do |format|
      format.html do redirect_to edit_project_group_path(@project, @project_group, tab: 'users') end
      format.js   do load_users; render action: 'change_members' end
    end
  end

  def remove_user

    @project_group.users.delete(User.find(params[:user_id]))
    respond_to do |format|
      format.html do redirect_to controller: '/project_groups', action: 'edit', id: @project_group, tab: 'users' end
      format.js   do load_users; render action: 'change_members' end
    end
  end

  def autocomplete_for_user
    @users = User.active.not_in_group(@project_group).like(params[:q]).limit(100)
    render layout: false
  end

  def create_memberships








  end

  alias :edit_membership :create_memberships

  def destroy_membership

    




  end

  protected

  def find_group

  end

  def default_breadcrumb





  end

  def show_local_breadcrumb

  end

  # Loads users not present in the group
  def load_users
    @users_not_in_group = User.active.not_in_group(@project_group).limit(100)
  end

  # Prevents access if the group is not a child of project
  def authorize_manageable
    unless @project_group.is_child_of?(@project)
      deny_access
    end
    true
  end
end

app/helpers/project_groups_helper.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2017 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2017 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++
require_dependency 'projects_helper'

module ProjectGroupsHelper
  def project_group_settings_tabs
    [{ name: 'general', partial: 'project_groups/general', label: :label_general },
     { name: 'users', partial: 'project_groups/users', label: :label_user_plural },
     { name: 'memberships', partial: 'project_groups/memberships', label: :label_project_plural }
    ]
  end

  # Generate link to a given project's settings
  # @param project [Project]
  # @param label [Symbol]
  # @param tab [String]
  def link_to_project_settings(project, label = :label_settings, tab = "project_groups")
    link_to l(:label_settings), controller: "projects", action: "settings", id: project, tab: tab
  end

  # A fancy wrapper for permission check
  # @param project [Project]
  # @param group [ProjectGroup]
  # @return [Bool]
  def can_manage_group?(project, group)
    group.is_child_of?(project)
  end

end

app/views/project_groups/_form.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2017 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<%#
  needs locals:
  f: labelled form builder
%>

<%= error_messages_for :project_group %>

<section class="form--section">
  <div class="form--field">
    <%= f.text_field :lastname,
                     label: ProjectGroup.human_attribute_name(:name),
                     required: true,
                     container_class: '-middle' %>
  </div>

  <%= render partial: 'customizable/form', locals: { form: f,
                                                     all_fields: true,
                                                     only_required: false } %>
</section>

app/views/project_groups/_general.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2017 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<%= labelled_tabular_form_for @project_group, url: project_group_path(@project, @project_group), html: {method: :put}, as: :project_group do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= styled_button_tag l(:button_save), class: '-highlight -with-icon icon-checkmark' %>
<% end %>

app/views/project_groups/_memberships.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2017 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>
<% projects = @project_group.projects %>

<div class="grid-block">
  <div class="grid-content">
    <% if @project_group.memberships.any? %>
      <div class="generic-table--container">
        <div class="generic-table--results-container">
          <table class="generic-table memberships">
            <colgroup>
              <col highlight-col>
              <col highlight-col>
              <col>
            </colgroup>
            <thead>
              <tr>
                <th>
                  <div class="generic-table--sort-header-outer">
                    <div class="generic-table--sort-header">
                      <span>
                        <%= Project.model_name.human %>
                      </span>
                    </div>
                  </div>
                </th>
                <th>
                  <div class="generic-table--sort-header-outer">
                    <div class="generic-table--sort-header">
                      <span>
                        <%= l(:label_role_plural) %>
                      </span>
                    </div>
                  </div>
                </th>
                <th><div class="generic-table--empty-header"></div></th>
              </tr>
            </thead>
            <tbody>
              <% @project_group.memberships.each do |membership| %>
                <% next if membership.new_record? %>
                  <tr id="member-<%= membership.id %>" class="class">
                    <td class="project"><%=h membership.project %></td>
                    <td class="roles">
                      <span id="member-<%= membership.id %>-roles"><%=h membership.roles.sort.collect(&:to_s).join(', ') %></span>
                    </td>
                  </tr>
              <% end %>
            </tbody>
          </table>
          
        </div>
      </div>
    <% else %>
      <%= no_results_box %>
    <% end %>
  </div>
  <div class="grid-content">
    <% if projects.any? %>
      <fieldset class="form--fieldset">
        <legend class="form--fieldset-legend"><%=l(:label_project_plural)%></legend>
        <div class="form--field -vertical">
          <div class="form--field-container -vertical">
            <% projects.each do |project| %>
              <li>
                <%= link_to project, project_path(project), title: project.short_description %>
              </li>
            <% end %>
          </div>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/project_groups/_users.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2017 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<div class="grid-block">
  <div class="grid-content">
    <% if @project_group.users.any? %>
      <div class="generic-table--container">
        <div id="group_users_table" class="generic-table--results-container">
            <%= render partial: 'project_groups/users_table' %>
        </div>
      </div>
    <% else %>
      <%= no_results_box %>
    <% end %>
  </div>
  <div class="grid-content">
    <% users = User
               .not_builtin
               .active
               .not_in_group(@project_group)
               .limit(100) %>
    <% if @users_not_in_group.any? %>
      <%= styled_form_tag(add_users_project_group_path(@project, @project_group),
                          method: :post,
                          remote: true,
                          'ajax-indicated': '') do |f| %>
        <remote-field-updater url="<%= url_for(controller: '/project_groups', action: 'autocomplete_for_user', id: @project_group)%>">
          <fieldset class="form--fieldset">
            <legend class="form--fieldset-legend"><%=l(:label_user_new)%></legend>
              <div class="form--field -vertical">
                <%= styled_label_tag "user_search", l(:label_user_search) %>
                <div class="form--field-container">
                  <%= styled_text_field_tag 'user_search',
                                            nil,
                                            class: 'remote-field--input',
                                            data: { :'remote-field-key' =>'q' } %>
                </div>
              </div>
              <div class="form--field -vertical">
                <div id="users" class="remote-field--target form--field-container -vertical">
                  <%= principals_check_box_tags 'user_ids[]', @users_not_in_group %>
                </div>
              </div>
          </fieldset>
        </remote-field-updater>
        <div>
          <%= styled_button_tag l(:button_add),
                                class: '-highlight -with-icon icon-checkmark' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/project_groups/_users_table.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2017 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<table class="generic-table users">
  <colgroup>
    <col highlight-col>
    <col>
  </colgroup>
  <thead>
  <tr>
    <th>
      <div class="generic-table--sort-header-outer">
        <div class="generic-table--sort-header">
                      <span>
                        <%= User.model_name.human %>
                      </span>
        </div>
      </div></th>
    <th><div class="generic-table--empty-header"></div></th>
  </tr>
  </thead>
  <tbody>
  <% @project_group.users.sort.each do |user| %>
      <tr id="user-<%= user.id %>">
        <td class="user"><%= link_to_user user %></td>
        <td class="buttons">
          <%= link_to l(:button_remove), remove_user_project_group_path(@project, @project_group, user_id: user ),
                      method: :post,
                      remote: :true,
                      'ajax-indicated': '',
                      class: 'icon icon-remove' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/project_groups/autocomplete_for_user.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2017 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<%= principals_check_box_tags 'user_ids[]', @users %>

app/views/project_groups/change_members.js.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2017 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

var tab = jQuery('#tab-content-users');
<% content = escape_javascript render(partial: 'project_groups/users') %>
var compiledContent = OpenProject.Helpers.Angular.compile('<%= content %>');

tab.html(compiledContent);

<% flash_message = escape_javascript render(partial: "members/common_notice",
                                            locals: { message: l(:notice_successful_update) }) %>
tab.prepend('<%= flash_message %>');

autoHideFlashMessage();

app/views/project_groups/change_memberships.js.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2017 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<% if @membership.valid? %>
  <% content = escape_javascript render(partial: 'memberships') %>
  <% flash_message = escape_javascript render(partial: "members/common_notice",
                                              locals: { message: l(:notice_successful_update) }) %>
  var compiledContent = OpenProject.Helpers.Angular.compile('<%= content %>');
  jQuery('#tab-content-memberships').html(compiledContent);

  jQuery('#tab-content-memberships').prepend('<%= flash_message %>');
<% else %>
  alert('<%= escape_javascript(l(:notice_failed_to_save_members, errors: @membership.errors.full_messages.join(', '))).html_safe %>');
<% end %>

autoHideFlashMessage();

app/views/project_groups/destroy_memberships.js.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2017 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<% content = escape_javascript render(partial: 'memberships') %>
<% flash_message = escape_javascript render(partial: "members/common_notice",
                                            locals: { message: l(:notice_successful_delete) }) %>
var compiledContent = OpenProject.Helpers.Angular.compile('<%= content %>');
jQuery('#tab-content-memberships').html(compiledContent);
jQuery('#tab-content-memberships').prepend('<%= flash_message %>');

app/views/project_groups/edit.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2017 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<% html_title @project, "#{l(:label_edit)} #{ProjectGroup.model_name.human} #{h @project_group.name}" %>

<% local_assigns[:additional_breadcrumb] = @project_group.name %>
<%= breadcrumb_toolbar @project_group.name %>
<%= render_tabs project_group_settings_tabs %>

app/views/project_groups/new.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2017 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<% html_title l(:label_administration), l("label_group_new") %>
<% local_assigns[:additional_breadcrumb] = l(:label_group_new) %>
<%= breadcrumb_toolbar l(:label_group_new) %>

<%= labelled_tabular_form_for(@project_group) do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <div><%= f.button l(:button_create), class: 'button -highlight -with-icon icon-checkmark' %></div>
<% end %>